spring:
  sql:
    init:
      mode: always
      continue-on-error: true

  datasource:
    url: jdbc:postgresql://localhost:5432/growdrip_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 5500

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE